### ISSUE TITLE
git branch

### ISSUE THREAD

**Issue by ntut-feng** [ntut-xuan/OOPL2022s#1]
助教你好
想問說在這次專案中，設置的方法是有一個main，然後2個人各自創一個自己的branch，在完成自己的部分之後再將自己的branch merge到main裡面嗎?
因為我們現在是一個人用main，一個人自己開一個分支，結果在要push時無法push，本來想說切換到main再push，結果在pull時顯示
![image](https://user-images.githubusercontent.com/126550515/224946708-0eb31621-3006-44d0-a98a-c936ec134be4.png)
後來使用強制覆蓋，卻回朔到原本的版本了

**Comment by c1ydehhx** [comment]
嗨，你的 issue 發錯地方了，你應該發到你自己的 repository 上。
